apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-application
  namespace: backend-namespace
  labels:
    app: backendapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backendapp
  template:
    metadata:
      labels:
        app: backendapp
    spec:
      containers:
        - name: myapp
          image: mustafaessam/backendsimpleapp:v55
          ports:
            - containerPort: 8081
              protocol: TCP
